package com.anthony.calculator;

/**
 * Created by anthonyjones on 4/28/17.
 */

public enum Operation {

    ADD, SUBTRACT, MULTIPLY, DIVIDE, CALCULATE_VARIABLE_EXP, SQUARE_ROOT,
    FACTORIAL, SQUARED, FAHRENHEIT_TO_CELSIUS, CELSIUS_TO_FAHRENHEIT,
    INVERT_SIGN, INVERSE_NUMBER, LOG, LOG_10, LOG_INVERSE, LOG_INVERSE_NATURAL_LOG,
    SINE, COSINE, TANGENT, INVERSE_SINE, INVERSE_COSINE, INVERSE_TANGENT
}
